services:
  app:
    build: .
    ports:
      - "7777:7777"

    depends_on:
      - mongo

    environment:
      PORT: 7777
      MONGO_URI: mongodb://appuser:password123@mongo:27017/mydb?authSource=mydb
      JWT_SECRET: codebuddy
      JWT_EXPIRES_IN: "60"

    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm dev

  mongo:
    image: mongo

    ports:
      - "27017:27017"

    command: ["mongod", "--auth", "--bind_ip_all"]

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123

    volumes:
      - mongo-data:/data/db
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongo-data:
