services:
  app:
    build:
      context: .
      args:
        DATABASE_URL: mongodb://appuser:password123@mongo:27017/mydb?authSource=mydb&replicaSet=rs0
    ports:
      - "7777:7777"

    depends_on:
      mongo:
        condition: service_healthy

    environment:
      PORT: 7777
      DATABASE_URL: mongodb://appuser:password123@mongo:27017/mydb?authSource=mydb&replicaSet=rs0

    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm dev

  mongo:
    image: mongo

    build:
      context: ./docker/mongo

    ports:
      - "27017:27017"

    command: ["mongod", "--auth", "--bind_ip_all", "--replSet", "rs0"]

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123

    volumes:
      - mongo-data:/data/db
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

    healthcheck:
      test: >
        mongosh --username admin --password admin123 --authenticationDatabase admin --eval "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongo:27017'}]}) }"
      interval: 5s
      timeout: 30s
      retries: 30

volumes:
  mongo-data:
